name: lost_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ## a b
  #=========== c
  cached_network_image:
  countries_utils: ^1.0.1
  cupertino_icons: ^1.0.2
  #===========  d
  dio: ^4.0.6
  #===========  e
  #=========== f
  flutter:
    sdk: flutter
  flutter_bloc:
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter_form_builder: ^7.0.0
  flutter_lints: ^1.0.4
  fluttertoast: ^8.0.8
  flutter_styled_toast: ^2.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  flutter_verification_code:
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.6.0
  #===========  g
  get_it: ^7.2.0
  #===========  h
  hexcolor: ^2.0.5
  http: ^0.13.4
  #===========  i
  image_picker:
  intl: 0.17.0
  #===========  j
  #===========  k
  #===========  l
  lint: ^1.8.2
  lottie: ^1.2.1
  #===========  m
  #===========  n
  notification_permissions: ^0.6.1
  #===========  o
  #===========  p
  path_provider: ^2.0.11
  pin_code_fields: ^7.3.0
  pull_to_refresh: 2.0.0
  #===========  q
  #===========  r
  #===========  s
  sliding_sheet: ^0.5.2
  smooth_page_indicator: ^1.0.0+2
  shared_preferences:
  shimmer: 2.0.0
  splashscreen: ^1.3.5
  #===========  t
  timeago: ^3.2.2
  timer_count_down: ^2.2.0
  #===========  u
  url_launcher: ^6.1.3
  #===========  v
  #===========  x
  #===========  y
  #===========  z


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal_medium.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
